apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.32.0"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/HV-Hung/homelab-gitops/main/infra/vault/server/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy: {}
