replicaCount: 1

image:
  repository: "ghcr.io/hv-hung/family-svc"
  tag: "latest"
env:
  - name: DB_HOST
    value: "postgresql.databases.svc.cluster.local"
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    value: "dev_user"
  - name: DB_NAME
    value: "dev"
  - name: DB_SSLMODE
    value: "disable"

secretRef:
  secretName: app-secret
  secrets:
    - name: DB_PASSWORD
      key: DB_PASSWORD

ingress:
  enabled: true
  className: "nginx"
  host: "family.hungops.tech"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

probes:
  liveness:
    enabled: true
    path: /healthz/live
    port: 8080
  readiness:
    enabled: true
    path: /healthz/ready
    port: 8080
