
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-db-secret
  namespace: databases
spec:
  vaultAuthRef: default
  mount: secret                   
  type: kv-v2                     
  path: admin
  
  destination:
    name: admin-db-secret          
    create: true
    
  refreshAfter: 60s

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dev-db-secret
  namespace: databases
spec:
  vaultAuthRef: default
  mount: secret                   
  type: kv-v2                     
  path: dev
  
  destination:
    name: dev-db-secret          
    create: true
    
  refreshAfter: 60s

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: prod-db-secret
  namespace: databases
spec:
  vaultAuthRef: default
  mount: secret                   
  type: kv-v2                     
  path: prod
  
  destination:
    name: prod-db-secret          
    create: true
    
  refreshAfter: 60s