apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    create: true
    name: app-secret
    overwrite: false
  hmacSecretData: true
  mount: secret
  path: {{ .Values.environment }}
  refreshAfter: 60s
  type: kv-v2
  vaultAuthRef: default
