apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-api-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/HV-Hung/homelab-gitops
    targetRevision: main
    path: apps/_chart
    helm:
      valueFiles:
        - ../../apps/prod/api-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
