apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tunnel-token
  namespace: cloudflare
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: cloudflare
  
  destination:
    name: tunnel-token
    create: true
    
  refreshAfter: 60s
